// All event types in the system
export const EVENT_TYPES = {
  // Platform connections
  PLATFORM_CONNECTED: 'PLATFORM_CONNECTED',
  PLATFORM_DISCONNECTED: 'PLATFORM_DISCONNECTED',
  
  // Products
  PRODUCT_SYNCED: 'PRODUCT_SYNCED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  INVENTORY_UPDATED: 'INVENTORY_UPDATED',
  
  // Offers
  OFFER_CREATED: 'OFFER_CREATED',
  OFFER_UPDATED: 'OFFER_UPDATED',
  OFFER_ACTIVATED: 'OFFER_ACTIVATED',
  OFFER_DEACTIVATED: 'OFFER_DEACTIVATED',
  OFFER_EXPIRED: 'OFFER_EXPIRED',
  OFFER_DELETED: 'OFFER_DELETED',
  
  // Streams
  STREAM_CREATED: 'STREAM_CREATED',
  STREAM_AUTO_DETECTED: 'STREAM_AUTO_DETECTED',
  STREAM_STARTED: 'STREAM_STARTED',
  STREAM_ENDED: 'STREAM_ENDED',
  STREAM_CANCELLED: 'STREAM_CANCELLED',
  
  // Replays
  REPLAY_CREATED: 'REPLAY_CREATED',
  REPLAY_AUTO_IMPORTED: 'REPLAY_AUTO_IMPORTED',
  REPLAY_PUBLISHED: 'REPLAY_PUBLISHED',
  REPLAY_VIEW: 'REPLAY_VIEW',
  REPLAY_CLICK: 'REPLAY_CLICK',
  
  // Moments
  MOMENT_CREATED: 'MOMENT_CREATED',
  MOMENT_UPDATED: 'MOMENT_UPDATED',
  MOMENT_DELETED: 'MOMENT_DELETED',
  
  // Short links
  LINK_CREATED: 'LINK_CREATED',
  LINK_CLICKED: 'LINK_CLICKED',
  LINK_REVOKED: 'LINK_REVOKED',
  
  // Checkout
  CHECKOUT_STARTED: 'CHECKOUT_STARTED',
  CHECKOUT_REDIRECTED: 'CHECKOUT_REDIRECTED',
  CHECKOUT_ABANDONED: 'CHECKOUT_ABANDONED',
  
  // Orders
  PURCHASE_COMPLETED: 'PURCHASE_COMPLETED',
  ORDER_UPDATED: 'ORDER_UPDATED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  ORDER_REFUNDED: 'ORDER_REFUNDED',
  
  // Inventory
  RESERVATION_CREATED: 'RESERVATION_CREATED',
  RESERVATION_CONFIRMED: 'RESERVATION_CONFIRMED',
  RESERVATION_RELEASED: 'RESERVATION_RELEASED',
  RESERVATION_EXPIRED: 'RESERVATION_EXPIRED',
  
  // Link in bio
  LINK_IN_BIO_VIEW: 'LINK_IN_BIO_VIEW',
  LINK_IN_BIO_CLICK: 'LINK_IN_BIO_CLICK',
} as const;

export type EventType = (typeof EVENT_TYPES)[keyof typeof EVENT_TYPES];

// Event metadata
export interface EventMetadata {
  source?: string;
  userAgent?: string;
  ipAddress?: string;
  correlationId?: string;
}

// Base event structure
export interface BaseEvent<T extends EventType, P> {
  eventId: string;
  eventType: T;
  creatorId?: string;
  payload: P;
  metadata?: EventMetadata;
  occurredAt: Date;
}
